### ISSUE TITLE
Create filter

### ISSUE THREAD

**Issue by AscanderS** [races1986/SafeLanguage#15]
Create a filter to split lines (paragraphs) into sentences.
As this filter runs before the upload of data, it belongs to the set of tools available in CEM/_s.

**Comment by AscanderS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create filter to split lines into paragraphs.](https://trello.com/c/OKufLpes/18-create-filter-to-split-lines-into-paragraphs)

**Comment by CooperData** [comment]
@AscanderS, using nltk.tokanize.sent_tokenize is a good option. I am importing the library anyway in the project so it could be reused.

**Comment by AscanderS** [comment]
Thanks @races1986. However, a simple split call did the trick for this filter.

Now I need to add a test file and I'm done.
