### ISSUE TITLE
Create md file about interaction between SafeLanguage and CEM-bot

### ISSUE THREAD

**Issue by CooperData** [races1986/SafeLanguage#9]
Create a markdown file to be added to docs to show what the interaction between CEM-bot and SafeLanguage will look like. 

Questions that should be answered: 
- Input & Output between CEM-Bot and SafeLanguage
    Best way to compartmentalize functionality
- Best place to store CEM-bot on SafeLanguage repo
    Should CEM-bot functionality be built as a mock object in SafeLanguage?

**Comment by CooperData** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Interaction between CEM-Bot and SafeLanguage](https://trello.com/c/CJkn3KwF/12-interaction-between-cem-bot-and-safelanguage)

**Comment by AscanderS** [comment]
Now the general md file explains the interaction.
